name: despliega en aws

on: workflow_dispatch

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
    - name: probando
      run: echo "job de prueba para dar tiempo"

  desploy:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@master
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
            
